[workspace]
members = [
    "renet",
    "demo_chat",
    "demo_bevy",
    "renetcode",
    "bevy_renet",
    "renet_visualizer",
    "renet_steam",
    "renet_webtransport",
    "renet_webtransport_server"
]
resolver = "2"
