[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
copyleft = "deny"
allow-osi-fsf-free = "either"
allow = [ 
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
 ]

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

# https://github.com/EmbarkStudios/cargo-deny/issues/389
[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "h3-webtransport"
expression = "MIT"
license-files = [{ path = "../LICENSE", hash = 0xbd0eed23 }]

[[licenses.exceptions]]
# https://github.com/emilk/egui/issues/2321
allow = ["LicenseRef-UFL-1.0"]
name = "epaint"

[bans]
multiple-versions = "allow"
wildcards = "allow"


[sources]
unknown-registry = "deny"
unknown-git = "deny"

allow-git = [
    # Unreleased version for steamworks, need release with PR https://github.com/Noxime/steamworks-rs/pull/134
    "https://github.com/Noxime/steamworks-rs",
    # Unreleased/breaking version for webtransport with the feature "i-implement-a-third-party-backend-and-opt-into-breaking-changes"
    "https://github.com/hyperium/h3"
]
