[package]
name = "renet_webtransport_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
renet = { path = "../../renet" }
renet_webtransport ={ path = "../../renet_webtransport" }